#!/bin/bash

docker stop mysqldb

docker run -d \
-p 3306:3306 \
--name mysqldb \
-e MYSQL_DATABASE=$MYSQL_DATABASE \
-e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
mysql

#NOTE - I'M PRETTY SURE THESE ENVIROMENT VARIABLES WON'T WORK OR BE LOADED, I MIGHT NEED TO MAKE ANOTHER SCRIPT FOR IT
